[package]
name = "cargo-contract"
version = "0.3.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2018"

license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/paritytech/cargo-contract"
documentation = "https://substrate.dev/substrate-contracts-workshop/#/"
homepage = "https://www.parity.io/"
description = "Setup and deployment tool for developing Wasm based smart contracts via ink!"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["cli", "tool"]

[dependencies]
env_logger = "0.7"
anyhow = "1.0"
structopt = "0.3"
log = "0.4"
heck = "0.3"
zip = { version = "0.5", default-features = false }
pwasm-utils = "0.12"
parity-wasm = "0.41"
cargo_metadata = "0.9"

sp-core = { git = "https://github.com/paritytech/substrate/", package = "sp-core", optional = true }
subxt = { git = "https://github.com/paritytech/substrate-subxt/", rev = "a9df35c570afdf7f5b081acb09dcf06fc3e5ad42", package = "substrate-subxt", optional = true }
tokio = { version = "0.1", optional = true }
futures = { version = "0.1", optional = true }
url = { version = "1.7", optional = true }
hex = { version = "0.4.0", optional = true }

[build-dependencies]
anyhow = "1.0"
zip = { version = "0.5", default-features = false }
walkdir = "2.2"

[dev-dependencies]
assert_matches = "1.3"
tempfile = "3.1"
wabt = "0.9"

[features]
default = []
extrinsics = ["sp-core", "subxt", "tokio", "futures", "url", "hex"]
test-ci-only = []
