# This file corresponds to the `.cargo/config.toml` file used for the `dylint` examples here:
# https://github.com/trailofbits/dylint/tree/master/examples.

[target.x86_64-apple-darwin]
linker = "dylint-link"

[target.x86_64-unknown-linux-gnu]
linker = "dylint-link"

[target.x86_64-pc-windows-msvc]
linker = "dylint-link"
