[package]
name = "contract-analyze"
version = "4.0.0-rc"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
contract-metadata = { version = "4.0.0-rc", path = "../metadata" }
parity-wasm = { version = "0.45.0", features = ["sign_ext"] }
anyhow = "1.0.75"

[dev-dependencies]
wabt = "0.10.0"
