[package]
name = "contract-transcode"
version = "2.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/cargo-contract"
documentation = "https://docs.rs/contract-transcode"
homepage = "https://www.substrate.io/"
description = "Library encoding calls for smart contracts on substrate"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
include = ["Cargo.toml", "*.rs", "LICENSE"]

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.69"
base58 = { version = "0.2.0" }
blake2 = { version = "0.10.4", default-features = false }
contract-metadata = { version = "2.1.0", path = "../metadata" }
escape8259 = "0.5.2"
hex = "0.4.3"
indexmap = "1.9.2"
ink_env = "4.0.1"
ink_metadata = "4.0.1"
itertools = "0.10.5"
tracing = "0.1.37"
nom = "7.1.3"
nom-supreme = { version = "0.7.0", features = ["error"] }
primitive-types = { version = "0.12.1", default-features = false, features = ["codec", "scale-info", "serde"] }
scale = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
scale-info = { version = "2.3.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.155", default-features = false, features = ["derive"] }
serde_json = "1.0.94"
thiserror = "1.0.39"

[dev-dependencies]
assert_matches = "1.5.0"
ink = "4.0.1"
sp-core = { version = "18.0.0", default-features = false }
sp-keyring = "21.0.0"

[features]
# This `std` feature is required for testing using an inline contract's metadata, because `ink!` annotates the metadata
# generation code with `#[cfg(feature = "std")]`.
default = ["std"]
std = []
