[package]
name = "contract-transcode"
version = "4.0.0-rc.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/cargo-contract"
documentation = "https://docs.rs/contract-transcode"
homepage = "https://www.substrate.io/"
description = "Library encoding calls for smart contracts on substrate"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
include = ["Cargo.toml", "*.rs", "LICENSE"]

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.78"
base58 = { version = "0.2.0" }
blake2 = { version = "0.10.6", default-features = false }
contract-metadata = { version = "4.0.0-rc.1", path = "../metadata" }
escape8259 = "0.5.2"
hex = "0.4.3"
indexmap = "2.1.0"
ink_env = "5.0.0-rc"
ink_metadata = "5.0.0-rc"
itertools = "0.12.0"
tracing = "0.1.40"
nom = "7.1.3"
nom-supreme = { version = "0.7.0", features = ["error"] }
primitive-types = { version = "0.12.2", default-features = false, features = ["codec", "scale-info", "serde"] }
scale = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.52"
strsim = "0.10.0"

[dev-dependencies]
assert_matches = "1.5.0"
ink = "5.0.0-rc"
sp-core = "22.0.0"
sp-keyring = "25.0.0"

[features]
# This `std` feature is required for testing using an inline contract's metadata, because `ink!` annotates the metadata
# generation code with `#[cfg(feature = "std")]`.
default = ["std"]
std = []
