name: check
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
jobs:
  build-contract-template:
    strategy:
      matrix:
        config:
          - {
            os: "ubuntu-latest",
            optUrl: "https://github.com/WebAssembly/binaryen/releases/download/version_109/binaryen-version_109-x86_64-linux.tar.gz",
            optName: "wasm-opt",
            optPath: "binaryen-version_109/bin/wasm-opt"
          }
          - {
            os: "macos-latest",
            optUrl: "https://github.com/WebAssembly/binaryen/releases/download/version_109/binaryen-version_109-x86_64-macos.tar.gz",
            optName: "wasm-opt",
            optPath: "binaryen-version_109/bin/wasm-opt"
          }
          - {
            os: "windows-latest",
            optUrl: "https://github.com/WebAssembly/binaryen/releases/download/version_109/binaryen-version_109-x86_64-windows.tar.gz",
            optName: "wasm-opt.exe",
            optPath: "binaryen-version_109/bin/wasm-opt.exe"
          }
    runs-on: ${{ matrix.config.os }}
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Checkout sources & submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install wasm-opt
        uses: engineerd/configurator@v0.0.8
        with:
          name: ${{ matrix.config.optName }}
          url: ${{ matrix.config.optUrl }}
          pathInArchive: ${{ matrix.config.optPath }}

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rust-src, clippy, rustfmt

      - name: Install cargo-dylint
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version ^2 cargo-dylint

      - name: Install dylint-link
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version ^2 dylint-link

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Template
        run: |
          wasm-opt --version
          cargo -vV
          cargo dylint --version
          cargo run -- contract --version
          cargo run -- contract new foobar
          echo "[workspace]" >> foobar/Cargo.toml
          cargo run -- contract build --manifest-path=foobar/Cargo.toml
          cargo run -- contract check --manifest-path=foobar/Cargo.toml
          cargo run -- contract test --manifest-path=foobar/Cargo.toml
