name: ci
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true
          components: rustfmt

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          components: clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Clippy with features
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --profile debug-ci --all-features --all-targets -- -D warnings

      - name: Clippy without features
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --profile debug-ci --all-targets -- -D warnings

  test:
    strategy:
      fail-fast: false
      matrix:
        # We want newer versions than 'latest' here to have current wasm-opt
        os: ["ubuntu-22.04", "macos-12", "windows-2022"]
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install wasm-opt
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install binaryen

      - name: Install wasm-opt
        if: ${{ runner.os == 'macOS' }}
        run: brew install binaryen

      - name: Install wasm-opt
        if: ${{ runner.os == 'Windows' }}
        uses: engineerd/configurator@v0.0.9
        with:
          name: wasm-opt.exe
          url: https://github.com/WebAssembly/binaryen/releases/download/version_109/binaryen-version_109-x86_64-windows.tar.gz
          pathInArchive: binaryen-version_109/bin/wasm-opt.exe

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          target: wasm32-unknown-unknown
          components: rust-src

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-dylint
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-dylint
          version: 2

      - name: Install dylint-link
        uses: baptiste0928/cargo-install@v1
        with:
          crate: dylint-link
          version: 2

      - name: Download and run latest `substrate-contracts-node` binary for macOS
        if: runner.os == 'macOS' 
        run: |
            curl -L -o substrate-contracts-node.zip 'https://gitlab.parity.io/parity/mirrors/substrate-contracts-node/-/jobs/artifacts/main/download?job=build-mac' && \
            unzip substrate-contracts-node.zip && \
            chmod +x artifacts/substrate-contracts-node-mac/substrate-contracts-node &&
            ./artifacts/substrate-contracts-node-mac/substrate-contracts-node -linfo,runtime::contracts=debug  2>&1 | tee /tmp/contracts-node.log &
      
      - name: Install and run latest `substrate-contracts-node` binary for windows-2022
        if: runner.os == 'Windows' 
        run: |
            cargo install contracts-node --git https://github.com/paritytech/substrate-contracts-node.git --force --locked && \
            substrate-contracts-node -linfo,runtime::contracts=debug  2>&1 | tee /tmp/contracts-node.log &

      - name: Run Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --profile debug-ci --all-features -- --test-threads=1

  template:
    strategy:
      fail-fast: false
      matrix:
        # We want newer versions than 'latest' here to have current wasm-opt
        os: ["ubuntu-22.04", "macos-12", "windows-2022"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install wasm-opt
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get install binaryen

      - name: Install wasm-opt
        if: ${{ runner.os == 'macOS' }}
        run: brew install binaryen

      - name: Install wasm-opt
        if: ${{ runner.os == 'Windows' }}
        uses: engineerd/configurator@v0.0.9
        with:
          name: wasm-opt.exe
          url: https://github.com/WebAssembly/binaryen/releases/download/version_109/binaryen-version_109-x86_64-windows.tar.gz
          pathInArchive: binaryen-version_109/bin/wasm-opt.exe

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          target: wasm32-unknown-unknown
          components: rust-src

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-dylint
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-dylint
          version: 2

      - name: Install dylint-link
        uses: baptiste0928/cargo-install@v1
        with:
          crate: dylint-link
          version: 2

      - name: Check Template
        run: >-
          wasm-opt --version &&
          cargo -vV &&
          cargo dylint --version &&
          cargo run --profile debug-ci -- contract --version &&
          cargo run --profile debug-ci -- contract new --target-dir ${{ runner.temp }} foobar &&
          cargo run --profile debug-ci -- contract build --manifest-path=${{ runner.temp }}/foobar/Cargo.toml &&
          cargo run --profile debug-ci -- contract check --manifest-path=${{ runner.temp }}/foobar/Cargo.toml &&
          cargo run --profile debug-ci -- contract test --manifest-path=${{ runner.temp }}/foobar/Cargo.toml &&
          cargo run --profile debug-ci -- contract build --manifest-path=${{ runner.temp }}/foobar/Cargo.toml --release
