name: dependabot-auto-merge
on:
  pull_request:
jobs:
  merge:
    runs-on: ubuntu-latest
    # run action only on dependabot branches
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{ steps.app-token.outputs.token }}
