name: release-verifiable-image
on:
  push:
    branches:
      - 'master'
  release:
    types:
      - edited
      - prereleased
      - published
env:
  IMAGE_NAME: paritytech/contracts-verifiable

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image from master
        if: ${{ github.event_name == "push" }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./build-image/Dockerfile
          push: true
          build-args: |
            CARGO_CONTRACT_GIT="https://github.com/paritytech/cargo-contract"
            CARGO_CONTRACT_BRANCH="master"
          tags: |
            ${{ env.IMAGE_NAME }}:master
            ${{ env.IMAGE_NAME }}:latest

      - name: Build and push Docker image from release
        if: ${{ github.event_name == "release" }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./build-image/Dockerfile
          push: true
          build-args: |
            CARGO_CONTRACT_GIT="https://github.com/paritytech/cargo-contract"
            CARGO_CONTRACT_TAG=${{ github.event.release.tag_name }}
          tags: ${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}

