name: continuous-intergration/windows

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
      - '.gitlab-ci.yml'

jobs:
  check:
    name: build-contract-template
    strategy:
      matrix:
        platform:
          - windows-latest
        toolchain:
          - stable
    runs-on: ${{ matrix.platform }}
    env:
      RUST_BACKTRACE: full
    steps:

      - uses: engineerd/configurator@v0.0.8
        with:
          name: "wasm-opt.exe"
          url: "https://github.com/WebAssembly/binaryen/releases/download/version_109/binaryen-version_109-x86_64-windows.tar.gz"
          pathInArchive: "binaryen-version_109/bin/wasm-opt.exe"

      - name: Checkout sources & submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rust-src

      - name: Install cargo-dylint
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-dylint
          version: 2

      - name: Install dylint-link
        uses: baptiste0928/cargo-install@v1
        with:
          crate: dylint-link
          version: 2

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: Output versions
        run: |
          wasm-opt --version
          cargo -vV
          cargo dylint --version

      - name: Build contract template on ${{ matrix.platform }}-${{ matrix.toolchain }}
        run: |
          cargo run -- contract --version
          cargo run -- contract new foobar
          echo "[workspace]" >> foobar/Cargo.toml
          cargo run -- contract build --manifest-path=foobar/Cargo.toml
          cargo run -- contract check --manifest-path=foobar/Cargo.toml
          cargo run -- contract test --manifest-path=foobar/Cargo.toml

      # This stage has to be deactivated until https://github.com/Vurich/crunchy/pull/10
      # is merged and released.
      # - name: Run tests on {{ matrix.platform }}-${{ matrix.toolchain }}
      #  # The tests take a long time in the GitHub Actions runner (~30 mins),
      #  # hence we run them only on `master`.
      #  if: github.ref == 'refs/heads/master'
      #  run: |
      #    cargo test --verbose --workspace --all-features
